steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/stratos-repo/stratos-app:', '.']

  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev//stratos-repo/stratos-app:']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'stratos-app'
      - '--image'
      - 'us-central1-docker.pkg.dev//stratos-repo/stratos-app:'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev//stratos-repo/stratos-app:'
